name: Day 40 - First GitHub Actions Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello from GitHub Actions, Deepika Sri! 🚀"

      - name: Print Date and Time
        run: date

      - name: Print Triggering Branch Name
        run: echo "Triggered on branch: ${{ github.ref_name }}"

      - name: List Repository Files
        run: ls -la

      - name: Print Runner OS Info
        run: uname -a
