name: Day 40 First Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello from GitHub Actions, Deepika Sri!"

      - name: Print Date
        run: date

      - name: Print Branch
        run: echo "Branch name is main"

      - name: List Files
        run: ls -la

      - name: Print OS
        run: uname -a
